var langboxvisible = false
function langbox() {
    var langstyle = document.querySelector("#hi1style")
    if (langboxvisible === false) {
        langstyle.innerHTML = "<style>#lang-box {visibility: visible; height: auto; width: 20vw;}</style>"
        langboxvisible = true
    } else {
        langstyle.innerHTML = "<style>#lang-box {visibility: hidden; height: 0; width: 0;}</style>"
        langboxvisible = false
    }
}

var plchldr = document.querySelector("#place")
if (plchldr) {
    var placeholder = ""
    var cities = ["Bratislava", "Viedeň", "Berlín", "Londýn"] // update after connect database
    var currentCityIndex = 0
    var charIndex = 0
    var isDeleting = false

    setInterval(function () {
        const currentCity = cities[currentCityIndex];

        placeholder = currentCity.slice(0, charIndex++);
        if (charIndex - 1 > currentCity.length) {
            placeholder = ""
            currentCityIndex = (currentCityIndex + 1) % cities.length
            charIndex = 0
        }

        document.querySelector('#place').placeholder = placeholder
    }, 500);
}

// this part will be moved to php file after connect database
var htlslst = document.querySelector("#hotelslist")
if (htlslst) {
    // this part will be generated by php
    var hotels = [
        {
            name: "Penzión U Martiny",
            location: "Bratislava",
            price: 105,
            rating: 1,
            img: "https://bratislavskykraj.sk/wp-content/uploads/2020/02/bratislavsky_hrad.jpg",
            list_num: 1,
            url: "hotel.html"
        },
        {
            name: "Hotel Grand Wien",
            location: "Viedeň",
            price: 65,
            rating: 5,
            img: "https://www.placesofjuma.com/wp-content/uploads/2023/12/Wien-3b-scaled.jpg",
            list_num: 2,
            url: "hotel.html"
        },
        {
            name: "Hotel Haubtbahnhof",
            location: "Berlín",
            price: 72,
            rating: 4,
            img: "https://www.allianz-pro-schiene.de/wp-content/uploads/2015/10/Bahnhof_des_Jahres2007_berlin-hbf-aussenansicht-e1443778428171-1600x900.jpg",
            list_num: 3,
            url: "hotel.html"
        },
        {
            name: "Hostel Youth Greenwich",
            location: "Londýn",
            price: 20,
            rating: 3,
            img: "https://britainsbestguides.org/wp-content/uploads/2018/02/Britains-Best-Guides-Greenwich3.jpg",
            list_num: 1,
            url: "hotel.html"
        }
    ]
    // end

    hotels.forEach(hotel => {
        var hotelDiv = document.createElement("div")
        hotelDiv.className = `hotellist-c${hotel.list_num}`
        hotelDiv.onclick = function () {document.location.href = `${hotel.url}`}
        hotelDiv.innerHTML = `<img src="${hotel.img}" class="hotellist-img"><span class="hotellist-name">${hotel.name}</span><span class="hotellist-location">${hotel.location}</span><span class="hotellist-price">${hotel.price}€</span><span class="hotellist-rating">${hotel.rating}★</span>`
        htlslst.appendChild(hotelDiv)
    })
}
// end